### PR TITLE
Stylization/Color Scheme Closes #48

### LINKED ISSUE #48: As a user, I want a consistent color theme throughout the app, in order to make the app more aesthetically appealing

### PR DESCRIPTION
**Pull request by lrondenet**

### CODE REVIEW

**Review by e7ite — APPROVED** [review]
Cool!

**Comment by bmarden** [comment]
I pulled this down, and it looks like the images/pic.png doesn't exist? Can you add that as a commit?

Also the fonts/Nunito-Black.ttf file is missing. Probably just need to commit the images/ and fonts/ folders

**Comment by lrondenet** [comment]
Okay! 👍 I added the image and the fonts.

**Comment by bmarden** [comment]
Cool! Looks good!

**Review by bmarden — APPROVED** [review]

**Review by asheelamagwili — APPROVED** [review]
Yay styling!!

**Pull request merged**
