### PR TITLE
Home styling

### PR DESCRIPTION
**Pull request by bmarden**
I removed most of the comments from main.dart again because they didn't really make sense within the context anymore. Renamed and moved the MyHomePage class to screens/home/home.dart and called it from main.dart. 

The appTheme function sets the overall theme via theme/style.dart. This way we can change the theme of the whole project by changing just one file as long as we are consistent when using colors throughout the app. 

Also added a side drawer which is like a pop out menu with some template items on there that we can change around. Added a button on the home page to just see what something like that would look like. 

Let me know what you guys think.

### CODE REVIEW

**Review by asheelamagwili — APPROVED** [review]
Everything looks good to me, pulling to my local to test out with my current work.

**Review by e7ite — CHANGES_REQUESTED** [review]
Could you please add a few brief comments on what does what so we can all understand?

**Review by lrondenet — APPROVED** [review]

**Review by lrondenet — APPROVED** [review]

**Comment by bmarden** [comment]
Added some comments that will hopefully clarify some of the functionality.

**Review by e7ite — APPROVED** [review]
Thanks for adding comments! Looks great!

**Pull request merged**
