### PR TITLE
Create proj template

### PR DESCRIPTION
**Pull request by bmarden**

### CODE REVIEW

**Review by asheelamagwili — APPROVED** [review]
Skeleton project approved

**Review by lrondenet — APPROVED** [review]

**Comment by e7ite** [comment]
Hello world

**Review by e7ite — APPROVED** [review]
Hello world

**Review by lrondenet — COMMENTED** [review]
hi

**Review by lrondenet — APPROVED** [review]

**Review by asheelamagwili — APPROVED** [review]
Skeleton project approved

**Pull request merged**
